version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pos-postgres
    environment:
      POSTGRES_DB: pos_db
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_password_2024
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pos-network

volumes:
  postgres_data:
    driver: local

networks:
  pos-network:
    driver: bridge